const reactRules = {
  'react/button-has-type': 'error',
  'react/destructuring-assignment': ['error', 'always'],
  'react/display-name': 'off',
  'react/forbid-foreign-prop-types': 'error',
  'react/jsx-boolean-value': ['error', 'never'],
  'react/jsx-filename-extension': 'off',
  'react/jsx-fragments': ['error', 'element'],
  'react/jsx-handler-names': 'error',
  'react/jsx-no-bind': ['error', { allowArrowFunctions: true }],
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-no-literals': 'error',
  'react/jsx-no-target-blank': 'error',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-pascal-case': 'error',
  'react/jsx-props-no-multi-spaces': 'error',
  'react/no-typos': 'error',
  'react/sort-comp': [
    'error',
    {
      order: [
        'state',
        'instance-variables',
        'instance-methods',
        'lifecycle',
        'render',
      ],
    },
  ],
  'react/jsx-sort-default-props': 'error',
  'react/jsx-sort-props': ['error', { reservedFirst: true }],
  'react/jsx-tag-spacing': 'error',
  'react/jsx-wrap-multilines': 'error',
  'react/no-access-state-in-setstate': 'error',
  'react/no-array-index-key': 'error',
  'react/no-danger': 'error',
  'react/no-did-mount-set-state': 'error',
  'react/no-did-update-set-state': 'error',
  'react/no-find-dom-node': 'error',
  'react/no-is-mounted': 'error',
  'react/no-multi-comp': 'error',
  'react/no-render-return-value': 'error',
  'react/no-string-refs': 'error',
  'react/no-this-in-sfc': 'error',
  'react/no-unsafe': 'error',
  'react/no-unused-prop-types': 'error',
  'react/no-unused-state': 'error',
  'react/no-will-update-set-state': 'error',
  'react/prefer-es6-class': ['error', 'always'],
  'react/prefer-stateless-function': 'error',
  'react/require-render-return': 'error',
  'react/self-closing-comp': 'error',
  'react/sort-prop-types': 'error',
  'react/static-property-placement': ['error', 'property assignment'],
  'react/style-prop-object': 'error',
  'react/void-dom-elements-no-children': 'error',
};

export default reactRules;
